modules/elasticsearch/monitoring/facets.yaml
modules/mongo/monitoring/facets.yaml
modules/mysql/monitoring/facets.yaml
modules/mysql/web_ui/0.1/facets.yaml
modules/postgres/monitoring/facets.yaml
modules/redis/monitoring/facets.yaml
modules/service/monitoring/facets.yaml

Change k8s cloud to kubernetes in monitoring modules

---

modules/service/deployment/0.1/facets.yaml
modules/service/statefulset/0.1/facets.yaml

spec.runtime.metrics for service(deploy,sts)

---

.github/workflows/innersourcing/cleanup.py
.github/workflows/preview.yml

versioning fix in github actions

---

intents/ingress/facets.yaml

Adds the missing outputs from ingress intent.

Add outputs to ingress intent

---

modules/cassandra/k8s/0.1/facets.yaml
modules/elasticsearch/k8s/0.1/facets.yaml
modules/elasticsearch/k8s/0.2/facets.yaml
modules/ingress/nginx_k8s_native/0.1/facets.yaml
modules/kafka/k8s/0.2/facets.yaml
modules/kafka/k8s/0.3/facets.yaml
modules/mongo/k8s/0.2/facets.yaml
modules/mongo/k8s/0.3/facets.yaml
modules/mysql/k8s/0.1/facets.yaml
modules/mysql/k8s/0.2/facets.yaml
modules/postgres/k8s/0.1/facets.yaml
modules/postgres_user/default/0.3/facets.yaml
modules/rabbitmq/k8s/0.1/facets.yaml
modules/redis/k8s/0.1/facets.yaml
modules/service/deployment/0.1/facets.yaml
modules/service/statefulset/0.1/facets.yaml
modules/tcp_lb/nlb/0.1/facets.yaml
modules/tcp_lb/nlb/0.2/facets.yaml
modules/vault/k8s/0.1/facets.yaml

Added CPU and memory limit for service and redis k8s flavor

Add cpu and memory limits to all

---

modules/postgres_user/default/0.3/facets.yaml
modules/postgres_user/default/0.3/locals.tf
modules/postgres_user/default/0.3/main.tf

- **replace _ with - in grant statement name**
- **use md5 hash if name length greater than 53**
Added the database name with underscores, when creating helm release it was changed to hyphen.

pg grant stmt fix

---

modules/kubernetes_cluster/gcp_gke/0.1/facets.yaml
modules/network/gcp_vpc/0.1/facets.yaml

Gcp launch wizard [Testing]

---

index.json
modules/kubernetes_cluster/default/0.1/facets.yaml
modules/network/default/0.1/facets.yaml

Default yaml cluster network

---

modules/kubernetes_cluster/aws_eks/0.1/facets.yaml
modules/kubernetes_cluster/aws_eks/0.2/facets.yaml
modules/network/aws_vpc/0.1/facets.yaml

Aws launch wizard merge

---

modules/kubernetes_cluster/default/0.1/facets.yaml
modules/network/default/0.1/facets.yaml

Default k8s and network typo merge 

---

index.json

Removing extra fields that backend does not read

Clean index.json

---

intents/aws_eventbridge/facets.yaml
modules/aws_eventbridge/default/0.1/facets.yaml
modules/aws_eventbridge/default/0.1/iam.tf
modules/aws_eventbridge/default/0.1/main.tf
modules/aws_eventbridge/default/0.1/outputs.tf
modules/aws_eventbridge/default/0.1/variables.tf
outputs.index.json
outputs/aws_eventbridge/output.facets.yaml

Creating event bridge from module in `facets-iac`:
Release Link:  https://facetsdemo.console.facets.cloud/capc/stack/infra-dev/releases/cluster/62970be8920da80001f3f495/dialog/release-details/67d015af0303790007da5938
Selective release after preview module is registered:
Release Link: https://facetsdemo.console.facets.cloud/capc/stack/infra-dev/releases/cluster/62970be8920da80001f3f495/dialog/release-details/67d0318c4781380007521c0f

migrate aws_eventbridge

---

.github/workflows/preview.yml

updated preview action to not trigger if there are no tf files

---

.github/workflows/intent.yml
intents/sns/facets.yaml

Working fine:
https://github.com/Facets-cloud/facets-modules/actions/runs/13830484490

Fix intent.yml GH action

---

intents/aws_event_bus/facets.yaml
modules/aws_event_bus/default/0.1/facets.yaml
modules/aws_event_bus/default/0.1/main.tf
modules/aws_event_bus/default/0.1/outputs.tf
modules/aws_event_bus/default/0.1/variables.tf
modules/aws_event_bus/default/0.1/versions.tf
outputs/aws_event_bus/output.facets.yaml

Proofs
1. Index working
2. Form working
3. matches module from s3
4. release link - https://facetsdemo.console.facets.cloud/capc/stack/infra-dev/releases/cluster/64b0fe30f8ae8b0007f5f010/dialog/release-details/67c6d54c438af40007ca6aad

Added aws event bus Module

---

modules/s3/default/0.2/facets.yaml

S3 import 

---

modules/kubernetes_cluster/aws_eks/0.1/facets.yaml
modules/kubernetes_cluster/aws_eks/0.2/facets.yaml

- allow reclaim policy to be configured for default storage class gp3 from json

allow reclaim policy to be configured for default storage class gp3 from json

---

index.json
intents.index.json
intents/image_pull_secret_injector/facets.yaml
modules/image_pull_secret_injector/default/0.1/facets.yaml
modules/image_pull_secret_injector/default/0.1/locals.tf
modules/image_pull_secret_injector/default/0.1/main.tf
modules/image_pull_secret_injector/default/0.1/outputs.tf
modules/image_pull_secret_injector/default/0.1/variables.tf

This PR adds a new module called `image_pull_secret_injector` to automatically injects image pull secrets into Kubernetes namespaces or workloads, ensuring seamless access to private container registries
https://app.clickup.com/t/86cy5wv8y
Release URL (Artifactories resource) - [https://facetsdemo.console.facets.cloud/capc/stack/infra-dev/releases/cluster/62970be8920da8[…]3f495/dialog/release-details/67dbcae05b0fe9000723985f](https://facetsdemo.console.facets.cloud/capc/stack/infra-dev/releases/cluster/62970be8920da80001f3f495/dialog/release-details/67dbcae05b0fe9000723985f)
Release URLs
- [https://facetsdemo.console.facets.cloud/capc/stack/infra-dev/releases/cluster/62970be8920da8[…]3f495/dialog/release-details/67dbeef05b0fe90007f41fe9](https://facetsdemo.console.facets.cloud/capc/stack/i …

[S78] Feature: Image Pull Secret Injector Module

---

modules/aws_waf/default/0.1/locals.tf
modules/aws_waf/default/0.1/main.tf
modules/aws_waf/default/0.1/outputs.tf
modules/aws_waf/default/0.1/variables.tf

This PR adds AWS WAF sypport
https://app.clickup.com/t/86cy3t9nk
Moved AWS WAF module from our IAC repo

[S78] Feature: AWS WAF

---

.github/workflows/innersourcing/zip_modules.py

Github Actions Fix

---

index.json

Just a addition of module ref in the index json
Main PR - https://github.com/Facets-cloud/facets-modules/pull/309
https://app.clickup.com/t/86cybk9dp

Fix: AWS OpenSearch 0.2 in index json

---

modules/s3/default/0.2/facets.yaml

Fix s3 import

---

modules/elasticsearch/opensearch/0.2/facets.yaml

Fix: Added cluster_config attribute from UI

---

index.json

addig postgres external to index.json

add postgres/external to index.json

---

modules/kubernetes_cluster/aws_eks/0.1/facets.yaml
modules/kubernetes_cluster/aws_eks/0.2/facets.yaml
modules/kubernetes_cluster/azure_aks/0.1/facets.yaml
modules/kubernetes_cluster/gcp_gke/0.1/facets.yaml
modules/network/aws_vpc/0.1/facets.yaml
modules/network/azure_vpc/0.1/facets.yaml
modules/network/gcp_vpc/0.1/facets.yaml

Forms for launch wizard
Task Id: https://app.clickup.com/t/86cxvhwj3
https://app.clickup.com/t/86cxvhw76
- AZURE
- GCP
- AWS

added launch wizard changes

---

index.json

- **add support for workload identity**
- **form changes**
- **shorten output name**
- **name changes for gcp sa**
- **fix version in index.json**

workload identity

---

outputs.index.json

fix output name workload identity

---

index.json
intents.index.json
intents/cloud_account/facets.yaml
modules/cloud_account/aws/0.1/facets.yaml
modules/cloud_account/aws/0.1/locals.tf
modules/cloud_account/aws/0.1/outputs.tf
modules/cloud_account/aws/0.1/variables.tf
modules/cloud_account/azure/0.1/facets.yaml
modules/cloud_account/azure/0.1/locals.tf
modules/cloud_account/azure/0.1/outputs.tf
modules/cloud_account/azure/0.1/variables.tf
modules/cloud_account/gcp/0.1/facets.yaml
modules/cloud_account/gcp/0.1/locals.tf
modules/cloud_account/gcp/0.1/outputs.tf
modules/cloud_account/gcp/0.1/variables.tf
outputs.index.json
outputs/cloud_account/output.facets.yaml

Tested in facets-iac
https://github.com/Facets-cloud/facets-iac/pull/1562

add cloud accounts for gcp, aws and azure

---

modules/config_map/k8s/0.3/facets.yaml
modules/kubernetes_secret/k8s/0.3/facets.yaml

Develop cm secret changes

---

modules/kubernetes_cluster/aws_eks/0.1/facets.yaml
modules/kubernetes_cluster/aws_eks/0.2/facets.yaml

Support to add custom iam policies for eks node pools
Task Id: https://app.clickup.com/t/86cyheyq9

Eks node iam policies

---

.github/workflows/innersourcing/zip_modules.py
index.json
intents.index.json
outputs.index.json

Reverts Facets-cloud/facets-modules#325

Revert "Remove index.json files"

---

intents/network/facets.yaml

removed outputs from intent/network

---

modules/helm/k8s/0.1/facets.yaml

support numbers as well in helm chartname

---

.github/workflows/innersourcing/zip_modules.py

zip modules fix

---

.github/workflows/preview.yml

Reverts Facets-cloud/facets-modules#337

Revert "Recursive preview to preview a module"

---

intents/network/facets.yaml
modules/kubernetes_cluster/aws_eks/0.1/facets.yaml
modules/kubernetes_cluster/aws_eks/0.2/facets.yaml
outputs/aws_vpc/output.facets.yaml

Reverts Facets-cloud/facets-modules#333

Revert "added outputs for vpc"

---

modules/elasticsearch/k8s/0.2/facets.yaml

Fix elasticsearch k8s 0.2 schema

---

modules/aws_eventbridge/default/0.1/facets.yaml
modules/cloudfront/default/0.1/facets.yaml
modules/ecs_service/default/0.1/facets.yaml
modules/ecs_service/default/0.2/facets.yaml
modules/kafka/msk/0.1/facets.yaml
modules/kms/default/0.1/facets.yaml
modules/kubernetes_cluster/aws_eks/0.1/facets.yaml
modules/kubernetes_cluster/aws_eks/0.2/facets.yaml
modules/kubernetes_cluster/azure_aks/0.1/facets.yaml
modules/kubernetes_cluster/gcp_gke/0.1/facets.yaml
modules/network/aws_vpc/0.1/facets.yaml
modules/network/azure_vpc/0.1/facets.yaml
modules/network/gcp_vpc/0.1/facets.yaml
modules/postgres/alloydb/0.1/facets.yaml
modules/postgres/aurora/0.1/facets.yaml
modules/postgres/cloudsql/0.2/facets.yaml
modules/postgres/external/0.1/facets.yaml
modules/postgres/k8s/0.1/facets.yaml
modules/postgres/rds/0.1/facets.yaml
modules/postgres/rds/0.2/facets.yaml
modules/postgres_user/default/0.3/facets.yaml
modules/redis/azure_cache/0.1/facets.yaml
modules/redis/elasticache/0.2/facets.yaml
modules/redis/memorystore/0.2/facets.yaml
modules/service/cronjob/0.1/facets.yaml
modules/service/deployment/0.1/facets.yaml
modules/service/job/0.1/facets.yaml
modules/service/statefulset/0.1/facets.yaml
modules/sns/default/0.1/facets.yaml

Standardize spec for json schema

---

modules/cloud_account/aws/0.1/facets.yaml
modules/cloud_account/azure/0.1/facets.yaml
modules/cloud_account/gcp/0.1/facets.yaml
modules/config_map/k8s/0.2/facets.yaml
modules/config_map/k8s/0.3/facets.yaml
modules/ecs_service/default/0.1/facets.yaml
modules/ecs_service/default/0.2/facets.yaml
modules/kubernetes_secret/k8s/0.1/facets.yaml
modules/kubernetes_secret/k8s/0.2/facets.yaml
modules/kubernetes_secret/k8s/0.3/facets.yaml
modules/postgres/external/0.1/facets.yaml

Add descriptions

---

modules/mongo_user/default/0.2/facets.yaml
modules/mysql_user/default/0.2/facets.yaml
modules/postgres_user/default/0.2/facets.yaml

Typos and fixes in forms

---

modules/config_map/k8s/0.3/facets.yaml

Updated description in ConfigMap 0.3
None

Fix: Updated description in ConfigMap 0.3

---

.github/workflows/innersourcing/generate_output_trees.py

Fix upload outputs script

---

modules/azure_functions/default/0.1/facets.yaml
modules/azure_functions/default/0.1/main.tf
modules/azure_functions/default/0.1/outputs.tf
modules/azure_functions/default/0.1/variables.tf
modules/azure_functions/default/0.1/windows.tf

Azure function module migration 

---

modules/google_cloud_storage/default/0.1/facets.yaml
modules/google_cloud_storage/default/0.2/facets.yaml
outputs/google_cloud_storage_bucket/output.facets.yaml

removed duplicate outputs for gcs

---

modules/service/deployment/0.1/facets.yaml
modules/service/statefulset/0.1/facets.yaml

This is a new and clean branch, as there where a large no. of merge conflicts i was getting this PR so i have created cherry picked my last commit from this PR https://github.com/Facets-cloud/facets-modules/pull/373 and then resolved the conflicts. This is clean now.

removed items from exec commands

---

modules/service/statefulset/0.1/facets.yaml

sts flavor

---

modules/google_cloud_storage/default/0.2/facets.yaml

Reverts Facets-cloud/facets-modules#455

Revert "remove inputs from gcs 0.2"
